### ISSUE TITLE
Where and when can i  read your paper released ?

### ISSUE THREAD

**Issue by SHUSHENGQIGUI** [yingcong/SemanticComponent#1]
I am so excited to learn  your research about attributes manipulation. So  I just want to learn about your research early. Thank you !!

**Comment by yingcong** [comment]
Hi, sorry for the late reply. It is available here 
http://appsrv.cse.cuhk.edu.hk/~ycchen/pdfFiles/SCNet.pdf

Thank you!

**Comment by SHUSHENGQIGUI** [comment]
thank you very much ! ! !
------------------
马骋复旦大学2018级大数据学院
TEL：18217751165
 

 




------------------ 原始邮件 ------------------
发件人: "Ying-Cong Chen"<notifications@github.com>;
发送时间: 2019年6月10日(星期一) 上午10:53
收件人: "yingcong/SemanticComponent"<SemanticComponent@noreply.github.com>;
抄送: "MACHENG"<cheng_ma18@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yingcong/SemanticComponent] Where and when can i  read yourpaper released ? (#1)




Hi, sorry for the late reply. It is available here
 http://appsrv.cse.cuhk.edu.hk/~ycchen/pdfFiles/SCNet.pdf
 
Thank you!
